(ns project-euler.core)

; f we list all the natural numbers below 10 that are multiples of 3 or 5,
; we get 3, 5, 6 and 9. The sum of these multiples is 23.
; Find the sum of all the multiples of 3 or 5 below 1000.
(defn multiples-of-3-and-5
  [coll]
  (apply + (filter #(zero? (min (mod % 5) (mod % 3))) coll)))


;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms will
;; be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not
;; exceed four million, find the sum of the even-valued terms.
(defn fib
  [a b]
  (cons a (lazy-seq (fib b (+ b a)))))

(take 10 (fib 1 2))

(defn even-fibonacci-numbers
  []
  (apply +  (filter even? (take-while #(< % 4e6) (fib 1 2)))))



; The prime factors of 13195 are 5, 7, 13 and 29.
; What is the largest prime factor of the number 600851475143
(defn largest-prime-factor
  []
  0)
